services:
  api:
    build: .
    container_name: api # 使用唯一的容器名
    restart: unless-stopped
    ports:
      - "2002:5000" # 外部端口2002映射到容器内部5000端口
    volumes:
      # 挂载代码以实现热更新
      - ./run.py:/app/run.py
      - ./project:/app/project
      # 挂载init文件夹
      - ./init:/app/init

      # 将实例文件夹持久化
      - ./instance:/app/instance
      # SQL文件目录挂载
      - ./sql:/app/sql
    environment:
      - FLASK_APP=run
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
      # --- 数据库连接信息 ---
      - DATABASE_URL=postgresql://user:password@db:5432/rewards_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rewards_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db-service # 使用唯一的容器名
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rewards_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Shanghai
    volumes:
      # 将 PostgreSQL 数据持久化到宿主机的 ./data 目录
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
